### ISSUE TITLE
duplicated faces using read.wrl

### ISSUE THREAD

**Issue by Celli119** [zarquon42b/RvtkStatismo#4]
It seems the read.wrl function duplicates the faces of the imported mesh. I'm not sure about it, but it may comes from [here](https://github.com/zarquon42b/RvtkStatismo/blob/master/src/readVTP.cpp#L73-L74).

**Comment by zarquon42b** [comment]
Thanks. Fixed in a79e43fc78f7ee7ebf138ce7fa7875763bd496a8
