### ISSUE TITLE
Downloading mesheR and RvtkStatismo from Github failing

### ISSUE THREAD

**Issue by stevenagl12** [zarquon42b/RvtkStatismo#6]
I have downloaded Rtools35 and have used the install_github function from devtools to attempt to install on a Windows 10 pc. I am unable to do so however, and keep getting the error: Error: Failed to install 'RvtkStatismo-master.zip' from local:
  (converted from warning) installation of package ‘C:/Users/STEVEN~1/AppData/Local/Temp/RtmpqKSq4b/remotes319873b75273/RvtkStatismo-master’ had non-zero exit status
I tried to download the zip file itself and use devtools install_local to install it and it is giving me the same error, so I tried to install using install(path to folder) and got: ./configure.win: line 22: cmake: command not found
: cannot stat 'Makefile': No such file or directory
ERROR: configuration failed for package 'RvtkStatismo'
* removing 'D:/Redirects/Documents/R/win-library/3.6/RvtkStatismo'
Error in (function (command = NULL, args = character(), error_on_status = TRUE,  : 
  System command error
I also tried using the R gui and got the same results. How can I download and install these packages?

**Comment by stevenagl12** [comment]
Also, I have tried with both R 3.5 and 3.6.

**Comment by zarquon42b** [comment]
RvtkStatismo does not work on Windows natively (I stated this in the README).
However, on my blog is a workaround using the embedded Linux: http://zarquon42b.github.io/2017/10/06/WSL-RvtkStatismo/ and there are a  couple of researchers I know of that use it without issues.

**Comment by stevenagl12** [comment]
I am still having an issue with being able to run the Rstudio on the MobaXterm. After following your instructions, when I run rstudio it says: bash: /usr/bin/rstudio: cannot execute binary file: Exec format error.

**Comment by stevenagl12** [comment]
Also, in order to run the code you sent me, I need mesheR. When I try to install that in linux I still get the non-zero exit status.

**Comment by zarquon42b** [comment]
> I am still having an issue with being able to run the Rstudio on the MobaXterm. After following your instructions, when I run rstudio it says: bash: /usr/bin/rstudio: cannot execute binary file: Exec format error.

Did you install the correct binary (64bit)?

> Also, in order to run the code you sent me, I need mesheR. When I try to install that in linux I still get the non-zero exit status.

With what error status?
Can you run "R" in the ubuntu bash shell?

**Comment by zarquon42b** [comment]
I googled you error message and it seems that recent rstudio versions [do not longer run on WSL](https://github.com/rstudio/rstudio/issues/3615), however, you can try an older version from here (I just tried rstudio-1.1.463-amd64.deb and  it worked): https://support.rstudio.com/hc/en-us/articles/206569407-Older-Versions-of-RStudio
How to install: Assuming, you have downloaded _rstudio-1.1.463-amd64.deb_ to C:\Users\<Username>\Downloads, do the following in your ubuntu shell:
```
cd /mnt/c/Users/<Username>/Downloads/
dpkg -i rstudio-1.1.463-amd64.deb # this will give you an error to be fixed with:
apt install -f #to fix missing dependencies
```


The mesheR error was related to a recent update of a dependency package, I fixed that now.

**Comment by stevenagl12** [comment]
So, I managed to get Rstudio up and running, but your code didn't work for me. I had to download libgstreamer0 and plugins from:
[https://packages.debian.org/jessie/amd64/libgstreamer0.10-0/download](url)
[https://packages.debian.org/jessie/amd64/libgstreamer-plugins-base0.10-0/download](url)
and then do this:
`sudo apt-get install gdebi-core
sudo dpkg -i libgstreamer0.10-0_0.10.36-1.5_amd64.deb 
sudo dpkg -i libgstreamer-plugins-base0.10-0_0.10.36-2+deb8u1_amd64.deb
sudo gdebi rstudio-1.1.463-amd64.deb`
This finally allowed me to run rstudio, however, I am still getting the non-zero exit status for mesheR.

**Comment by stevenagl12** [comment]
Is there another way to download mesheR?

**Comment by zarquon42b** [comment]
Hi Steven, I just tried and could install mesheR without issues on WSL (however, this is not a RvtkStatismo issue, so I will close this issue)
