### ISSUE TITLE
Restricting a SSM to + or - 1 or 2 standard deviations from the mean?

### ISSUE THREAD

**Issue by greglahsal21** [zarquon42b/RvtkStatismo#7]
How would you go about retrieving a model from a SSM that represents the models displacement 1 or 2 standard deviations from the mean shape and controlling whether it is + or - the standard deviation(s).

**Comment by zarquon42b** [comment]
```r
DrawSample(mymodel,-2) ## -2sd of 1st PC
DrawSample(mymodel,c(0,2)) # +2sd of 2nd PC
DrawSample(mymodel,c(0,0,3)) # +3sd of 3rd PC
etc..
```
