### ISSUE TITLE
cmake install fails due to outdated VTK repo URL

### ISSUE THREAD

**Issue by dfsp-spirit** [zarquon42b/RvtkStatismo#8]
When following the installation instructions for MacOS:

```
git clone https://github.com/statismo/statismo.git
mkdir build && cd build
cmake ../statismo/superbuild 
make ## make a coffee or go for lunch
````
...the final `make` step fails with:

```
Scanning dependencies of target VTK
[ 22%] Creating directories for 'VTK'
[ 25%] Performing download step (git clone) for 'VTK'
Cloning into 'VTK'...
fatal: unable to connect to vtk.org:
vtk.org[0: 66.194.253.19]: errno=Operation timed out

Cloning into 'VTK'...
fatal: unable to connect to vtk.org:
vtk.org[0: 66.194.253.19]: errno=Operation timed out

Cloning into 'VTK'...
fatal: unable to connect to vtk.org:
vtk.org[0: 66.194.253.19]: errno=Operation timed out

-- Had to git clone more than once:
          3 times.
CMake Error at VTK-prefix/tmp/VTK-gitclone.cmake:66 (message):
  Failed to clone repository: 'git://vtk.org/VTK.git'
```

Full error log here: https://pastebin.com/Y8u4DD4y

I think the reason is that the URL for the VTK git repo has changed.

**Comment by zarquon42b** [comment]
This is a problem of upstream statismo. Can you please open an issue there?

**Comment by dfsp-spirit** [comment]
Sure, I just noticed that I was in the wrong repo and that statismo is not RvtkStatismo. Sorry for the noise & thanks for the quick answer.

**Comment by dfsp-spirit** [comment]
Just a side note: the installation instructions for statismo that are [given on their repo website](https://github.com/statismo/statismo) differ from the method you suggest. They suggest:

```
$ brew tap homebrew/science
$ brew install statismo 
$ statismo-buid-gp-model -h
```

But nevermind updating, their instructions don't work either. I have [opened an issue over there](https://github.com/statismo/statismo/issues/279), but judging from the comments on the other open issues, [nobody seems to be working on it anymore](https://github.com/statismo/statismo/issues/277).

I guess I will try the Linux version later at home and look at your Travis config, here at the institute I only have MacOS.

**Comment by zarquon42b** [comment]
Sorry, as I do not own a MacOS PC my tests are a couple of years old. However, with the Linux version, I will definitely be able to help you and can assure you tha it works (I am using it pretty much daily) ;)
